---
- name: Configure Azure VM
  hosts: web
  become: yes

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Java
      apt:
        name: openjdk-17-jdk
        state: present

    - name: Verify Java
      command: java -version
      register: java_output
      ignore_errors: yes

    - debug:
        var: java_output.stderr_lines
